version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:9.9.0
    steps:
      - checkout
      - run: node --version
      - persist_to_workspace:
          root: .
          paths:
            - '*'
  test:
    docker:
      - image: circleci/node:9.9.0
    steps:
      - attach_workspace:
          at: .
      - run: node --version

